config/routes.rb
Rails.application.routes.draw do
  root 'records#index'
  resources:records

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  validates :title, :amount, :date, presence: :true

   def self.balance
     where("amount >= 0").sum(:amount)
   end

   def self.debt
     where("amount < ?", 0).sum(:amount)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # before_action :find_record, only: [:edit, :update, :destroy]

  def index
    @records = Record.all
    @total = Record.sum(:amount)
    @balance = Record.balance
    @debt = Record.debt
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.create(record_params)
    if @record.valid?
      flash[:notice] = "Congratulations! Successfully created the financial record!"
    else
      flash[:alert] = "Failed to create the financial record!"
    end
    # redirect_to :controller => "records", :action => "index"
    redirect_to records_path
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      flash[:success] = "Your record has been updated!"
      redirect_to root_path
    else
      flash[:alert] = "Failed to update the Record..."
      redirect_to edit_record_path(@records)
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    flash[:notice] = "A record has been deleted!"
    redirect_to root_path
  end

  private

  def record_params
    params.require(:record).permit(:title, :amount, :date)
  end

  # def find_record
  #   @record = Record.find(params[:id])
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PAISA</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700|Tillana:400,700" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div id="wrap">
    <%= render 'shared/nav' %>
    <div class="container">
      <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1">
          <%= render 'shared/flash' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div> <!-- #WRAP -->
  <%= render 'shared/footer' %>
</body>
</html>

app/views/records/delete.html.erb
<h1>Records#delete</h1>
<p>Find me in app/views/records/delete.html.erb</p>

app/views/records/edit.html.erb
<%= simple_form_for @record, method: :patch do |f| %>
  <%= f.input :title %>
  <%= f.input :amount %>
  <%= f.input :date %>
  <%= f.submit 'Update Record', class: 'btn btn-success'  %>
<% end %>

app/views/records/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h2><%= "Balance: #{@balance}" %></h2>
    <h2><%= "Debt: #{@debt}" %></h2>
    <h2><%= "Total: #{@total}" %></h2>
    <br>
    <div class="btn-group" role="group">
    </div>
  </div>
</div>


<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Amount</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
      <tr>
        <td><%= record.date %></td>
        <td><%= record.title %></td>
        <td><%= record.amount %></td>
        <td><%= link_to 'Edit', edit_record_path(record), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Delete', record_path(record), method: :delete, class: 'btn btn-danger' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/records/new.html.erb
<%= simple_form_for @record do |f| %>
  <%= f.input :title %>
  <%= f.input :amount %>
  <%= f.input :date %>
  <%= f.submit 'Create Record', class: 'btn btn-success'  %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <p>
    <a href="#" class='footer-brand'>PAISA</a>
    by
    <span id='dev'>TECHRISE</span>
    <br>
    © <%= Date.today.year %> All Rights Reserved
  </p>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to 'PAISA', root_path, class: 'brand-name' %>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'New Record', new_record_path %></li>

    </ul>
  </div><!-- /.container-fluid -->
</nav>